import { ArrowBigRightDash, ArrowBigUp, Brain, BrainCogIcon, BrainIcon, CornerRightUp, MenuSquare } from "lucide-react";
import type { Metadata } from "next";
import GlobalSidebar from "../../ui/ai-prompt-sidebar";


export const metadata: Metadata = {
  title: "Zen / AI",
  description: "Generated by create next app",
};

export default function AI() {

    return(
        <div className="ai-page">
            <GlobalSidebar>
                <div className="ai-context-form">
                    <div className="tab-btns">
                        <button className="tab active" id="fitnessTab">Fitness</button>
                        <button className="tab" id="foodTab">Food</button>
                    </div>
                    <div className="inputs">
                        <input type="number" id="age" name="age" min={11} max={100} placeholder="Age"/>
                        <input min={40} type="number" id="weight" name="weight" placeholder="Weight"/>
                        <input type="number" id="calories" name="calories" placeholder="Maintenance calories" min={0}/>
                        {/* <textarea id="goals" name="goals" placeholder="Goals and milestones for your journey"></textarea>  */}
                    </div>
                </div>
            </GlobalSidebar>
            <section className="ai-section">
                <div className="ai-input">
                    <button className="prompt-menu-btn"><BrainIcon /></button>
                    <div className="ai-text-wrapper">
                        <textarea placeholder="Ask Gemini..." rows={1}></textarea>
                    </div>
                    <button className="ai-send-btn"><ArrowBigUp /></button>
                </div>
            </section>
        </div>
    );
}