import type { Metadata } from "next";
import GlobalSidebar from "../ui/global-sidebar";


export const metadata: Metadata = {
  title: "uHealth AI",
  description: "Generated by create next app",
};
 
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <main>
        <GlobalSidebar />
        {children}
    </main>
  );
}
