import type { Metadata } from "next";
import GlobalSidebar from "../ui/global-sidebar";


export const metadata: Metadata = {
  title: "Zen / AI",
  description: "Generated by create next app",
};
 
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="ai-page">
        <GlobalSidebar />
        {children}
    </div>
  );
}
