import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
// import { GeistSans } from "geist/font/sans";
import "./globals.scss";
import Header from "@/components/header/header";

const inter = Inter_Tight({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
