import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Header from "./ui/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
